# Discord Invite Link:
# https://discordapp.com/api/oauth2/authorize?client_id=668589877327298604&permissions=387136&scope=bot

# Your Twitch channel
channel: ""

# Your Twitch bot channel
botChannel: ""

# Your Twitch bot OAuth Token
botOAuthToken: ""

# Delay between each check if the channel is live (in milliseconds!)
isLiveCheckInterval: 300000


# Discord bot token
discordToken: ""

# Channel ID in which the messages should appear
discordChannelID: ""

# Discord bot admin role - Allows to perform admin commands
adminRoleName: ""